#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
CUSTOM_BUILD=${CUSTOM_BUILD}
----------------------------------------------------------------------
"

echo "Executing usermod..."
mkdir "/tmp/temphome"
usermod -d "/tmp/temphome" hotio
usermod -o -u "${PUID}" hotio
usermod -d "${CONFIG_DIR}" hotio
rm -rf "/tmp/temphome"
groupmod -o -g "${PGID}" hotio

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown hotio:hotio "${CONFIG_DIR}"

if [[ ! -f "${CONFIG_DIR}/Caddyfile" ]]; then
    echo "Installing default \"Caddyfile\"..."
    cp "${APP_DIR}/Caddyfile" "${CONFIG_DIR}/Caddyfile"
    chown hotio:hotio "${CONFIG_DIR}/Caddyfile"
fi

ln -sf "${APP_DIR}/caddy" "/usr/local/bin/caddy"

if [[ -n "${CUSTOM_BUILD}" ]]; then
    echo "Trying to use the custom build \"${CUSTOM_BUILD}\"..."
    builtin_version=$("${APP_DIR}/caddy" version)
    chmod +x "${CUSTOM_BUILD}"
    custom_version=$("${CUSTOM_BUILD}" version)
    if [[ "${builtin_version}" != "${custom_version}" ]]; then
        echo "There's a version mismatch, you should update your custom build!"
    fi
    echo "Built-in: ${builtin_version}"
    echo "Custom:   ${custom_version}"
    ln -sf "${CUSTOM_BUILD}" "/usr/local/bin/caddy"
fi

"/usr/local/bin/caddy" fmt "${CONFIG_DIR}/Caddyfile" --overwrite
chown hotio:hotio "${CONFIG_DIR}/Caddyfile"
