#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
CUSTOM_BUILD=${CUSTOM_BUILD}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/Caddyfile" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/Caddyfile] file."
    cp "${APP_DIR}/Caddyfile" "${CONFIG_DIR}/Caddyfile"
    find "${CONFIG_DIR}/Caddyfile" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

ln -sf "${APP_DIR}/caddy" "/usr/local/bin/caddy"

if [[ -n "${CUSTOM_BUILD}" ]]; then
    log_inf "Trying to use the custom build [${CUSTOM_BUILD}]."
    builtin_version=$("${APP_DIR}/caddy" version)
    chmod +x "${CUSTOM_BUILD}"
    custom_version=$("${CUSTOM_BUILD}" version)
    if [[ "${builtin_version}" != "${custom_version}" ]]; then
        log_wrn "There's a version mismatch, you should update your custom build."
    fi
    ln -sf "${CUSTOM_BUILD}" "/usr/local/bin/caddy"
fi

"/usr/local/bin/caddy" fmt "${CONFIG_DIR}/Caddyfile" --overwrite
find "${CONFIG_DIR}/Caddyfile" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
