#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

XDG_CONFIG_HOME="${CONFIG_DIR}" XDG_DATA_HOME="${CONFIG_DIR}" HOME="${CONFIG_DIR}" \
exec s6-setuidgid hotio "/usr/local/bin/caddy" run --config "${CONFIG_DIR}/Caddyfile" --adapter caddyfile
