#!/command/with-contenv bash
# shellcheck shell=bash

set -e

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/Caddyfile" ]]; then
    echo "Installing default \"Caddyfile\"..."
    cp "${APP_DIR}/Caddyfile" "${CONFIG_DIR}/Caddyfile"
    chown hotio:hotio "${CONFIG_DIR}/Caddyfile"
fi

if [[ ! -d "${CONFIG_DIR}/fail2ban" ]]; then
    echo "Installing default \"fail2ban\"..."
    cp -R "${APP_DIR}/fail2ban" "${CONFIG_DIR}/"
    chown -R hotio:hotio "${CONFIG_DIR}/fail2ban"
fi

if [[ -f "${CONFIG_DIR}/fail2ban/fail2ban.sqlite3" ]]; then
    chown hotio:hotio "${CONFIG_DIR}/fail2ban/fail2ban.sqlite3"
fi

if [[ ! -f "${APP_DIR}/templates/.copied" ]]; then
    echo "Installing default \"templates\"..."
    rm -rf "${CONFIG_DIR}/templates"
    cp -R "${APP_DIR}/templates" "${CONFIG_DIR}/"
    chown -R hotio:hotio "${CONFIG_DIR}/templates"
    touch "${APP_DIR}/templates/.copied"
fi

if [[ ! -d "${CONFIG_DIR}/crontab" ]]; then
    echo "Installing default \"crontab\"..."
    cp -R "${APP_DIR}/crontab" "${CONFIG_DIR}/"
    chown -R hotio:hotio "${CONFIG_DIR}/crontab"
fi

if [[ -f "${CONFIG_DIR}/crontab/default" ]]; then
    echo "Loading user provided \"crontab\" to system..."
    crontab "${CONFIG_DIR}/crontab/default"
fi

if [[ ! -d "${CONFIG_DIR}/logrotate" ]]; then
    echo "Installing default \"logrotate\"..."
    cp -R "${APP_DIR}/logrotate" "${CONFIG_DIR}/"
    chown -R hotio:hotio "${CONFIG_DIR}/logrotate"
fi
