#!/command/with-contenv bash
# shellcheck shell=bash

set -e

umask "${UMASK}"

if [[ ! -d "${CONFIG_DIR}/crontab" ]]; then
    echo "Installing default \"crontab\"..."
    cp -R "${APP_DIR}/crontab" "${CONFIG_DIR}/"
    chown -R hotio:hotio "${CONFIG_DIR}/crontab"
fi

echo "Loading user provided \"crontab\" to system..."
crontab "${CONFIG_DIR}/crontab/default"
