#!/command/with-contenv bash
# shellcheck shell=bash

set -e

umask "${UMASK}"

if [[ ! -d "${CONFIG_DIR}/crontabs" ]]; then
    echo "Creating \"${CONFIG_DIR}/crontabs\" directory..."
    mkdir "${CONFIG_DIR}/crontabs"
    chown hotio:hotio "${CONFIG_DIR}/crontabs"
fi
